name: luci_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0  
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  simple_connection_checker: ^0.2.1  

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
